### ISSUE TITLE
Request for StrictUnion (aka either this or that)

### ISSUE THREAD

**Issue by balupton** [andnp/SimplyTyped#76]
Would be nice to see this typescript library add the `StrictUnion` generic type

- https://stackoverflow.com/q/54064736/130638
- https://stackoverflow.com/a/52678379/130638

``` typescript

type UnionKeys<T> = T extends any ? keyof T : never;
type StrictUnionHelper<T, TAll> = T extends any ? T & Partial<Record<Exclude<UnionKeys<TAll>, keyof T>, never>> : never;
type StrictUnion<T> = StrictUnionHelper<T, T>

type A = { a: number }
type B = { b: number }

const unionList: Array<A | B> = [{ a: 1 }, { b: 2 }]
const unionListInvalid: Array<A | B> = [{ a: 1 }, { b: 2 }, { a: 1, b: 2 }]
// ^ not actually invalid

const strictUnionList: Array<StrictUnion<A | B>> = [{ a: 1 }, { b: 2 }]
const strictUnionListInvalid: Array<StrictUnion<A | B>> = [{ a: 1 }, { b: 2 }, { a: 1, b: 2 }]
// ^ invalid as expected
```

**Comment by Retsam** [comment]
Thanks for the suggestion (and the code!) @balupton; I've opened #77 to implement this.

**Comment by balupton** [comment]
Great. As this is merged and released, I will close this issue. Thanks everyone

**Comment by andnp** [comment]
Thanks for the feature request! I hadn't seen this before, but it seems quite useful.

**Comment by dragomirtitian** [comment]
The specific version of `StrictUnion` used here seems to have been broken in 3.4. I added an [issue](https://github.com/Microsoft/TypeScript/issues/30569) on the typescript repo, but the break may be intentional. If needed this version will work with 3.4 as well:

```ts

type StrictUnionHelper<T, TAllKeys extends PropertyKey> = T extends any ? T & Partial<Record<Exclude<TAllKeys, keyof T>, never>> : never;
type StrictUnion<T> = StrictUnionHelper<T, UnionKeys<T>>
```

If needed I can submit a PR if the new behavior makes it into the 3.4 release.

**Comment by andnp** [comment]
Hey, thanks for the heads up! I can't seem to reproduce this locally with the latest `typescript@next` (version: `3.4.0-dev.20190323`).

Just out of curiosity, are you using `simplytyped@2.0.0` or higher? I think that PR #88 made strict union work for 3.4 a couple of weeks ago.

**Comment by dragomirtitian** [comment]
@andnp You are right, it was fixed by #88, my bad.

**Comment by andnp** [comment]
No worries! It was hidden away in a major version release, so it's not surprising that you hadn't seen it.

I usually try pretty hard to avoid bug fixes going in major versions, but I didn't find a way to fix this without dropping support for a few older typescript versions. Your solution looks like it would have worked with older TS versions though.

**Comment by balupton** [comment]
This is actually a fantastic use case for why abstracting these things out into a utility package (SimplyTyped) is such a good idea. As otherwise, everyone would need to go through this same debugging learning curve that you two just went through.

**Comment by dragomirtitian** [comment]
@andnp FYI, apparently this was a bug after all and the behavior has been fixed to work as before.
