### ISSUE TITLE
Suggestion: limit internal use of 'trivial' aliases to make more copy/paste friendly

### ISSUE THREAD

**Issue by Retsam** [andnp/SimplyTyped#89]
I've found myself copy-and-pasting from this library now-and-then: either into the TS playground or when people are looking for specific utilities (with credit). 

A couple internally-used aliases make that a little annoying: I've noticed `Keys`, `ObjectKeys`, and `AnyFunc` need to be replaced with the 'literal' equivalent, (or included in the snippet).

I definitely think dropping `Keys<T>` internally would be a good idea for this: as, AFAIR, it's just a aesthetic preference over `keyof T`.

I could go either way on the other two:

* `ObjectKeys` is more readable for anyone not familiar with the `keyof any` convention, but I do think that convention is *fairly* well known.  

* `AnyFunc<R>` is definitely shorter than `(...args: any[]) => R`; but I think the "inlined" version is pretty clear, too. (Unlike `keyof any`)  

In both cases, it's mostly a trade-off a readability vs. "copy-pastability".  It's not a huge deal either way, but I thought I'd include them, too.

**Comment by andnp** [comment]
Yeah, these are really good points. I've actually been thinking about changing the pitch of the library to being more focused towards being useful for learning more advanced types. I think reducing internal aliases would go well towards that goal.

`Keys<>` is totally aesthetic. My opinions about it have reduced notably recently, and I only use it now for consistency. I wouldn't be sad to see it disappear.

The `ObjectKeys` came about as an immediate response when keys became `Symbol | number` as well as `string`. I agree that `keyof any` has become more well known, so `ObjectKeys` is probably more of a historical artifact if anything. Besides, I've always regretted the name :laughing: 

I'm of two minds on `AnyFunc`. I _really_ don't like the way inline functions look and almost always use an alias for them. But I definitely like the idea of being able to copy/paste from the library easily.

---

I'll make several of these changes and think about `AnyFunc` some more too. I'll go ahead and make a PR that branches off of the currently open PR, that way all of this goes under the scope of `simplytyped@2.0.0` (downside to semantic-release is keeping major versions from creeping up quickly, though a totally utilitarian view _shouldn't_ care about that. I suppose I'm too sentimental).
