### ISSUE TITLE
Suggestion: add UnionToIntersection and Improve IntersectTuple 

### ISSUE THREAD

**Issue by JoshRosenstein** [andnp/SimplyTyped#97]
by adding the magical UnionToIntersection
```ts
type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends ((k: infer I) => void)
  ? I
  : never;
```
Ref: https://stackoverflow.com/questions/50374908/transform-union-type-to-intersection-type

Will give you a new feature and can replace :
```ts
export type IntersectTuple<T extends Vector<any>> =
    Length<T> extends 1 ? T[0] :
    Length<T> extends 2 ? T[0] & T[1] :
    Length<T> extends 3 ? T[0] & T[1] & T[2] :
    Length<T> extends 4 ? T[0] & T[1] & T[2] & T[3] :
    Length<T> extends 5 ? T[0] & T[1] & T[2] & T[3] & T[4] :
    Length<T> extends 6 ? T[0] & T[1] & T[2] & T[3] & T[4] & T[5] :
    Length<T> extends 7 ? T[0] & T[1] & T[2] & T[3] & T[4] & T[5] & T[6] :
    Length<T> extends 8 ? T[0] & T[1] & T[2] & T[3] & T[4] & T[5] & T[6] & T[7] :
    Length<T> extends 9 ? T[0] & T[1] & T[2] & T[3] & T[4] & T[5] & T[6] & T[7] & T[8] :
    Length<T> extends 10 ? T[0] & T[1] & T[2] & T[3] & T[4] & T[5] & T[6] & T[7] & T[8] & T[9] :
        any;
```
with:
```ts
export type IntersectTuple<T extends Vector<any>>=UnionToIntersection<T[number]>
```

**Comment by andnp** [comment]
This would be great! I was hesitant to add this at first because I wanted to be sure it was stable. These magical types make me nervous that the Typescript compiler will make internal changes and break the unsupported magic.

This type seems stable enough to me. If you'd like to add it, feel free to put up a PR! Otherwise I'll hopefully get around to it this weekend. I'll definitely be able to get to it by next weekend after a few deadlines cool down.

**Comment by andnp** [comment]
Oh also, I should note that you should avoid `extends any`. Re: the discussion in #88 :)

**Comment by JoshRosenstein** [comment]
@andnp  Will do! Also after seeing this issue and comment 
https://github.com/Microsoft/TypeScript/issues/29594#issuecomment-477068575  and also seeing tsc uses this [type](https://github.com/Microsoft/TypeScript/blob/4574c7a375064fbe22f194a13596330c4b29be19/src/compiler/types.ts#L6005-L6006)- not worried about stability.

I'll submit a PR when i get a chance. Thanks
